export default [
  {
    login: "EossForos",
    id: 49607514,
    node_id: "MDQ6VXNlcjQ5NjA3NTE0",
    avatar_url: "https://avatars.githubusercontent.com/u/49607514?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/EossForos",
    html_url: "https://github.com/EossForos",
    followers_url: "https://api.github.com/users/EossForos/followers",
    following_url: "https://api.github.com/users/EossForos/following{/other_user}",
    gists_url: "https://api.github.com/users/EossForos/gists{/gist_id}",
    starred_url: "https://api.github.com/users/EossForos/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/EossForos/subscriptions",
    organizations_url: "https://api.github.com/users/EossForos/orgs",
    repos_url: "https://api.github.com/users/EossForos/repos",
    events_url: "https://api.github.com/users/EossForos/events{/privacy}",
    received_events_url: "https://api.github.com/users/EossForos/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "Oganov2001",
    id: 69170739,
    node_id: "MDQ6VXNlcjY5MTcwNzM5",
    avatar_url: "https://avatars.githubusercontent.com/u/69170739?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Oganov2001",
    html_url: "https://github.com/Oganov2001",
    followers_url: "https://api.github.com/users/Oganov2001/followers",
    following_url: "https://api.github.com/users/Oganov2001/following{/other_user}",
    gists_url: "https://api.github.com/users/Oganov2001/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Oganov2001/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Oganov2001/subscriptions",
    organizations_url: "https://api.github.com/users/Oganov2001/orgs",
    repos_url: "https://api.github.com/users/Oganov2001/repos",
    events_url: "https://api.github.com/users/Oganov2001/events{/privacy}",
    received_events_url: "https://api.github.com/users/Oganov2001/received_events",
    type: "User",
    site_admin: false
  },
  {
    login: "Olga1506",
    id: 65306522,
    node_id: "MDQ6VXNlcjY1MzA2NTIy",
    avatar_url: "https://avatars.githubusercontent.com/u/65306522?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Olga1506",
    html_url: "https://github.com/Olga1506",
    followers_url: "https://api.github.com/users/Olga1506/followers",
    following_url: "https://api.github.com/users/Olga1506/following{/other_user}",
    gists_url: "https://api.github.com/users/Olga1506/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Olga1506/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Olga1506/subscriptions",
    organizations_url: "https://api.github.com/users/Olga1506/orgs",
    repos_url: "https://api.github.com/users/Olga1506/repos",
    events_url: "https://api.github.com/users/Olga1506/events{/privacy}",
    received_events_url: "https://api.github.com/users/Olga1506/received_events",
    type: "User",
    site_admin: false
  }
]
